<a href="https://colab.research.google.com/github/Arup3201/deep-learning-materials/blob/main/1_Basics_of_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Understanding Neural Networks with Examples

### Deep Learning in Nutshell

Programming has been the bread and butter for many developers since the discovery of computers.

Whenever developers needed to make any computer applications, they will usually break down the compononents of the applications and solve those compononents as individual problems and code their rules to solve that particular problem.

Let's say for example, we are to create a game for playing with ball. The ball can jump from down to up and whenever it hits the blocks at the top the blocks disappear and we get points. But, everytime when the ball comes down after hitting one or more blocks we need to catch that ball with a small black surface. If we fail to catch the ball then we will lose.

![Ball Game](https://www.heroconcept.com/wp-content/uploads/2018/09/breakout.jpg)

So, we break down the problem of creating this game into different problems and let's say we focus our attention to the problem of hitting the bricks at the top and controlling the balls movements after that.

```c
if(ball.collide(brick)) {
  removeBrick();
  ball.dx = -1*(ball.dx);
  ball.dy = -1*(ball.dy);
}
```

BUT, the question comes when we try to solve the problems which are more general and common but can't be easily expressed as rules by us.

You are asked to make an application that can detect whether a person is walking/running/biking/hiking?

![Problem with deep learning](https://i.postimg.cc/NMH9vhGv/problems-with-deep-learning-images.png)

What will you do?

Maybe for walking/runnung/hiking you can say
```c
if(speed < 4) {
  status=walking;
}
else if(speed < 10) {
  status=running;
}
else {
  status=biking;
}
```

But what about hiking?

How can you define it?

Even though walking/running/biking is not as simple as just mentioning their speed. Different person has different speeds and other factors like someone going up and down while running, how that looks like... all these things play an important role in determining their state.

That is where Machine Learning comes into picture.

Machine Learning is essentially doing the same thing but changing the same old way of writing code by yourself to define those rules.

When we talk about traditional programming, we had to define how walking looks like, how running looks like, how biking looks like etc...

![Deep Learning in Nutshell](https://i.postimg.cc/Bn4x5vSL/Deep-Learning-in-Nutshell.png)

Now, instead of you specifying how walking/running/biking/hiking look like (e.g. `speed < 4` or things like that), you provide how they looks like, when a person walks what it looks like, when a person runs what it looks like, along with the labels that labels those examples like if a person is walking then the label will be WALKING, if a person is running then label will be RUNNING and so on. And from that what we will get is the rules that define those states. *This is machine learning in nutshell*.

For example, when the machine learning system learns about all these states, maybe it will notice that when a person runs their feet will have a certain distance range, or when a person is biking their will be something like a cycle in the image, all this tiny tiny details will be taken into account by the system itself and it will automatically find out those rules/conditions when learning from the data and answers provided to it in this case they are images of people walking/running/biking/hiking and their labels.

In this notebook, we will look into some examples where we will create a neural network using tensorflow that will be able to learn the rules provided the data and answers to them. **Neural network is just an advance version of machine learning which is called deep learning.**

### Neural Networks with a simple example

*Neural Network is a a type of system which is able to find out the relation between it's input and output.*

For instance:

* $X => -2, -1, 0, 1, 2, 3$
* $Y => -5, -3, -1, 1, 3, 5$

**Find the relation between X and Y. Try to derive the Y from it's corresponding X value. E.g. How can -5 be generated from -2?**

Take some time to think...


If you guessed the relation to be $Y=2X-1$ then congratulations!!

That's right!! You are now able to what neural network does the things...

Let's try to think how we can come up with this equation...

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In this code block, we are creating a neural network using the `keras` API present in `tensorflow`. I am using a `Sequential` class which defines sequence of layers and providing one `Dense` layer inside it that has one neuron. It is taking 1 input at a time and it has an linear activation function to find the output. Don't worry if you do not understand any of these terms because in the next notebook we will discuss about them.

In [ ]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

You can think of this code shell as defining the neural network how it is going to calculate it's performance and with the help of it's performance how it is going to improve itself everytime to make itself perfect and learn the correct rule.

Think of it with the example, neural network at first don't know what is the relation between the X and Y, but it tries to guess that which is intially really bad. But, as it goes through the examples and calculates the output with its intially guessed rules, it finds out that those outputs are not exactly same as the output provided in the examples using the `loss`. So, then it improves it's guess with the help of `optimizer` and again starts guessing. The logic is every time the guess should be better than the previous one which is the job of optimizer. So, in short `loss` is calculates how good or how bad the current guess is, then gives the information to `optimizer` that helps to find better guesses by improving the current one.

As it approached towars the 100% accuracy we use the word `convergence`.

Remember one point here, `.compile` method does not tell the network to start guessing, instead it tells the network how the network is going to find about the performance(loss) and how it is going to improve(optimizer).

In [ ]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [ ]:
X = np.array([-2, -1, 0, 1, 2, 3], dtype=float)
Y = np.array([-5, -3, -1, 1, 3, 5], dtype=float)

# Y = 2X - 1

In [ ]:
model.fit(X, Y, epochs=100)

In [ ]:
model.predict([10.0])

1/1 [==============================] - 0s 96ms/step


array([[18.763657]], dtype=float32)

After learning from the examples, this model is able to predict the result for 10.0

Although the result is not exactly 19.0 but very close to 19.0

The reason is, our data is very small from which the model learnt so it was not able to learn everything and just from the 6 data points model will not have that much accuracy and confidence.

In [ ]:
model.get_weights()

[array([[1.9572951]], dtype=float32), array([-0.8092934], dtype=float32)]

From the result, you can see the coeffecient of X is very close to 2 and the bias value of close to -1.

### Another example to understand neural networks

In [ ]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

In [ ]:
xs = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)
ys = np.array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550])

# Y = 50X+ 50

In [ ]:
model.fit(xs, ys, epochs=100)

In [ ]:
model.predict([15])

1/1 [==============================] - 0s 66ms/step


array([[831.6896]], dtype=float32)

In [ ]:
15*50+50

800

In [ ]:
model.get_weights()

[array([[53.942387]], dtype=float32), array([22.553799], dtype=float32)]

### Neural Network with 2 inputs

In [ ]:
x1s = np.array([1, 2, 4, 6, 8, 10, 12], dtype=float)
x2s = np.array([2, 3, 4, 5, 6, 7, 8], dtype=float)
print(f"x1s shape={x1s.shape}")
print(f"x2s shape={x2s.shape}")

ys = np.array([ -6.5, -11.6, -14.7, -17.8, -20.9, -24. , -27.1], dtype=float)
print(f"ys shape={ys.shape}")

# Y = 2*X1 - 7.1*X2 + 5.7

x1s shape=(7,)
x2s shape=(7,)
ys shape=(7,)


In [ ]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])
model.compile(optimizer='sgd', loss='mean_squared_error')

In [ ]:
X = np.concatenate([x1s[:, np.newaxis], x2s[:, np.newaxis]], axis=-1)

X.shape

(7, 2)

In [ ]:
X

array([[ 1.,  2.],
       [ 2.,  3.],
       [ 4.,  4.],
       [ 6.,  5.],
       [ 8.,  6.],
       [10.,  7.],
       [12.,  8.]])

In [ ]:
model.fit(X, ys, epochs=100)

In [ ]:
model.predict([[10, 11]])

1/1 [==============================] - 0s 65ms/step


array([[-36.559517]], dtype=float32)

In [ ]:
2*10 - 7.1*11 + 5.7

-52.39999999999999

In [ ]:
model.get_weights()

[array([[-0.18278849],
        [-3.0789745 ]], dtype=float32),
 array([-0.86291295], dtype=float32)]

The coefficient of X1 is -0.17 and X2 is -3.09 which shows that neural network is far from accurate and the reason is simple, in this case we had to come up with the equation containing 2 variables and given the dataset is small such task is even difficult for us.

### Neural Network for Classification Problem

In [ ]:
xs = np.array([-10, -9, -8, -7, -6, -5, -4, -3,
               -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)
ys = np.array([0, 0, 0, 0, 0, 0, 0, 0,
               0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=float)

# 2*X - 5 > 0

In [ ]:
model = keras.Sequential(keras.layers.Dense(1,
                                            activation='sigmoid',
                                            input_shape=[1]))

In [ ]:
model.compile(optimizer='sgd', loss='binary_crossentropy')

In [ ]:
model.fit(xs, ys, epochs=100)

In [ ]:
model.predict([10.0])

1/1 [==============================] - 0s 75ms/step


array([[0.9948026]], dtype=float32)

In [ ]:
2*10-5 > 0

True

In [ ]:
model.get_weights()

[array([[0.5367841]], dtype=float32), array([-0.11345338], dtype=float32)]